name: CI/CD Fake
on: 
    workflow_dispatch:  
        #inputs:
            #ambiente:
                #type: choice
                #default: "desenvolvimento"
                #required: true
                #description: "Ambiente onde será feito o deploy"
                #options:
                  #- desenvolvimento
                  #- homologacao
                  #- producao
jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Build de Imagem Docker
              run: echo "Execução do comando de docker build"
            - name: Execução de Testes de Software
              run: echo "Aqui eu executo o teste de software"
            - name: Publicando a Release
              run: echo "Publicação da Relase final"   
    CD:
        needs: [CI]
        uses: joaohfm86/repo-reaproveitavel/.github/workflows/cd.yml@main
        #with:
          #ambiente: ${{ inputs.ambiente }}
        secrets:
          ambiente: ${{ secrets.AMBIENTE_ENTREGA }}